name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: 'node16'
        with:
          node-version: 12
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./ bootcampclassoneab.surge.sh --token ${{ secrets.SURGE_TOKEN }}
